version: '3.8'

services:
  db:
    container_name: db-mysql
    image: mysql
    #restart: always
    ports:
      - 3306:3306
    volumes:
      - '${PWD}/mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=mysql

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8083:8080