services:
  n8n:
    container_name: n8n-container
    image: n8nio/n8n:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 5678:5678
    volumes: 
      - '${PWD}/n8n_data:/home/node/.n8n'
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_development
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=postgres
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - '${PWD}/postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=n8n_development
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres