version: '3.8'

services:
  redis:
    container_name: redis-docker
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - 6379:6379
    volumes:
      - "${PWD}/redis_data:/bitnami/redis/data"
      - "${PWD}/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf "